### ISSUE TITLE
GeminiMulti got stuck when running

### ISSUE THREAD

**Issue by ShannonDaddy** [tamsen/Pisces#10]
Hi, I use GeminiMulti to realign my bam files, but got stuck, is this because of the big data size of the sample. When I use a sample with smaller data size, GeminiMulti finishes the whole realign process.  But I don't know how to solve the problem. I get some snapshots and the Gemini Log attched, please check them for me, thanks!

![image](https://user-images.githubusercontent.com/6656888/113111773-1bad4c80-923b-11eb-8ef4-875da27df3ae.png)
![image](https://user-images.githubusercontent.com/6656888/113111578-e43ea000-923a-11eb-92b7-787f29054af2.png)
![image](https://user-images.githubusercontent.com/6656888/113111609-ee609e80-923a-11eb-94d9-9a87f7b352eb.png)

[gemini_logs.zip](https://github.com/tamsen/Pisces/files/6276308/gemini_logs.zip)

**Comment by tamsen** [comment]
Hi there,

Can you pls re-attach those logs? For some reason, they are not downloading for me. Do you get a specific error message?

Hypothesis #1: its a size issue.
I just kicked off a Gemini job on a 5 GB sample I had. I will see if I can generate the same error you have. If its a size issue, hopefully this will trigger it.

Hypothesis #2: its a data issue.
If you chunk your failing bams into smaller bams (of the size that normally work for you, but all collectively containing all the same reads as the failing bam), do you still see the error? If yes -> data issue. If no -> memory/size issue.

thanks for your patience!

**Comment by ShannonDaddy** [comment]
> Hi there,
> 
> Can you pls re-attach those logs? For some reason, they are not downloading for me. Do you get a specific error message?
> 
> Hypothesis #1: its a size issue.
> I just kicked off a Gemini job on a 5 GB sample I had. I will see if I can generate the same error you have. If its a size issue, hopefully this will trigger it.
> 
> Hypothesis #2: its a data issue.
> If you chunk your failing bams into smaller bams (of the size that normally work for you, but all collectively containing all the same reads as the failing bam), do you still see the error? If yes -> data issue. If no -> memory/size issue.
> 
> thanks for your patience!

sorry，i re-attach the logs， please take a look, thanks!

**Comment by tamsen** [comment]
hi, ok got those logs now. Taking a look..

**Comment by tamsen** [comment]
Hi,

Thanks for your patience.

re Hypothesis #1: its a size issue.
OK, so I tested on a 5GB bam, and I had one crash (no exceptions reported, I (maybe?) blame our cluster, sometimes it kills off jobs) and 5 successes. I don't think its size. If you re-run your job does it always get stuck or is the issue intermittent? You could also try running on a different machine. I also tested my 5GB bam a few times on my personal box and no issue.

Hypothesis #2: its a data issue.
I need you to check this b/c I can't see your data. If you chunk your failing bams into smaller bams (of the size that normally work for you, but all collectively containing all the same reads as the failing bam), do you still see the error? 

sorry, these issues can be hard to resolve! Let me know if you have any more information I can run with.

best
Tamsen
