### ISSUE TITLE
Distribution of this fork on Bioconda

### ISSUE THREAD

**Issue by kbseah** [tamsen/Pisces#17]
Hello,

I'm coming here from Bioconda where a [pull request](https://github.com/bioconda/bioconda-recipes/pull/40636) has been made by @ok-gitr to update the `pisces` recipe to v5.3, and point the source url to this repository instead of the Illumina one.

It's not clear to us whether the existing recipe should be updated to point to this fork of the project, or if a new recipe under a different name should be created. I see that @tamsen is the main author of both versions, and that the version numbers follow sequentially.

The question is whether this fork is the "official" successor project, and whether the parent repository will continue to be updated and potentially have conflicting versioning.

Thanks for your input!

**Comment by tamsen** [comment]
Hi Brandon,

Thank you for all your work at Bioconda!

Yes, Pisces is no longer supported at illumina. The Bioconda recipe should be updated to point to https://github.com/tamsen/Pisces/ . This is where future releases will come from.

best
Tamsen

**Comment by kbseah** [comment]
Hi Tamsen, thanks for the clarification, and for continuing to maintain this software!
Cheers -- Brandon
