### ISSUE TITLE
WRONG VF FOR LOW FREQUENCY VARIANTS AND COMMA FORMAT 

### ISSUE THREAD

**Issue by AriadnaColmeneroCobo** [tamsen/Pisces#18]
Good morning,

I am using the following code to report variants for some targeted sequencing analysis samples.

After applying the following code, I could see how the low frequency variants were misreported. That is to say, in the other 3 variant callers I was getting a VAF, for example, of less than 0.01, while PISCES, of more than 0.2. At this point, I noticed that the VF was being reported with a ",", which is making me doubt that it is really OK, since the other variant callers report the VF with ".". I'm using PISCES/5.3.0.0-FORK (lastest version available).

Also, when I add the --MinVF 0.001 argument, it stops working. I understand why in this case it has a . and not a ",",....

```
## A.1) Gemini
bashArguments = "GeminiMulti -bam "+cleanBqsrBam+" -genome "+refGenomeFolder+" -samtools "+samtoolsPath+" --outFolder "+outDir+"/pisces/gemini/"+sample+" -numProcesses "+cpus+" -exepath "+geminiExePath

## A.2) Pisces

bashArguments = "Pisces -bam "+bamGemini+" -g "+refGenomeFolder+" -i "+targetBedFileIntervalList+" -UseStitchedXD TRUE -CallMNVs TRUE -MinBQ 30 -MinVF 0. 001 -MinMQ 10 --OutFolder "+outDir+"/pisces/pisces/"+sample+" --MaxNumThreads "+cpus
```

The line obtained taking into account that the VF is reported with a comma:

    `GT:GQ:AD:DP:VF:NL:SB` 0/1:43:155,9:164:0,55:20:-14,2244

In addition, I should add that the QUAL of these variants is variable, some of them reaching 100. It's a bit of a strange situation and I would need your help and advice. I already reported this issue on https://github.com/Illumina/Pisces/issues/74, but I'm already using the latest version, so I'm writing again for more help.

I've also made sure that it's not a bug in my text editor as the commas already appear if I open it with vim.

Thank you so much,

**Comment by tamsen** [comment]
Hi there,

Thank you for using Pisces. Let me try to address each of your questions:

So it looks like your MinVF argument has white space between the decimal and the zero following it? " -MinBQ 30 -MinVF 0. 001 -MinMQ 10" . Or at least, it does in the command you pasted into the issue box.

If the Pisces VF is 0.2 and the other callers get 0.01, that doesn't mean pisces is necessarily wrong. It might be calculating the numbers differently. Open the bam you put into Pisces (the gemini-built bam) in IGV or similar, and you might be able to see why Pisces gives the results it does. Gemini does read-stitching and local realignment around indels, and at low minimum variant frequencies Pisces filters base calls very aggressively.  There are many reasons why different variant callers might give different results. Or, you can try without gemini, and see if the results are more straight forward to interpret.

It seems to me that your `GT:GQ:AD:DP:VF:NL:SB` 0/1:43:155,9:164:0,55:20:-14,2244  has been edited by some program that isn't pisces. The apostrophes and commas should not originate within pisces, so I can't really speak to that.

Lastly, could you please explain more about the problem with QUAL being variable? The quality typically varies with the variant call, and is by default capped at 100.

Best
Tamsen
