### ISSUE TITLE
How to call complex variants with Pisces?

### ISSUE THREAD

**Issue by HEKntg** [tamsen/Pisces#19]
Hello,
Pisces helps me a lot.
Is there any option or any other tool for complex variants?
Thank you.

**Comment by tamsen** [comment]
Hi there,

Thank you for using pisces!  Scylla is a simple complex variant caller included in the pisces package (see wiki https://github.com/tamsen/Pisces/wiki and https://github.com/tamsen/Pisces/wiki/Scylla-5.2.10-Design-Document). Scylla can combine phased SNPs and indels into complex variants. You can use the -dist argument to specify the maximum allowable distance between the variants that can be phased.

best
Tamsen

**Comment by HEKntg** [comment]
Hi,
I'll try it! Thank you again!
