### ISSUE TITLE
Can I disable the flag BS when this filter is not used?

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [tamsen/Pisces#20]
In our test, we only obtained R1 reads. I was wondering if there is a way to not flag variants based on SB. Is this possible?

My code

```
apptainer exec --bind "$ref_folder":"$ref_folder" \
               "$pisces"  dotnet /app/Pisces_5.2.9.122/Pisces.dll \
               -bam  "${Sample_ID}"_FINAL_SORTED.bam \
               -g  "$piscesrefgenomefolder" \
               -o ./ \
               -i "$ampliconscoordenatesbed"  \
               --gvcf false \
               --minvq 20 \
               --maxvq 100 \
               --minbq 20 \
               --mindpfilter 5000 \
               --ssfilter False\
               --minmq 20 \
               --mindp 10 
```

and a couple of variants
```

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	2111700067_FINAL_SORTED.bam
chr5	171410472	.	G	C	80	LowDP;NC;SB	DP=14	GT:GQ:AD:DP:VF:NL:SB	0/1:80:4,6:14:0.429:20:-100.0000
chr5	171410482	.	A	T	100	LowDP;NC;SB	DP=969	GT:GQ:AD:DP:VF:NL:SB	0/1:100:919,49:969:0.051:20:-100.0000
```

I know that the tool is not filtering out variant based on SB but it is weird that the flag is still there.

**Comment by tamsen** [comment]
Hi, can you pls send me a small bam that reproduces this and I'll take a look? Pisces was designed with amplicons in mind, and it should handle sections where coverage only goes in one direction. In general these should not get flagged with SB. In your case it might be an interaction with all the other filters. I can take a look. 

You can also try the "-OutputSBFiles" option to output some extra files, which should show the counts in each direction, to verify the reads are only going in one direction. 

best
Tamsen

**Comment by Manuel-DominguezCBG** [comment]
Hello, 

please find in[ this link](https://drive.google.com/drive/folders/100ZEVvrCVcoKLJ79R7DlFRFHef1qKDGl?usp=sharing) a bam file and the VCF file as a result of analyzing the BAM with the exact code provided above.

Again it can be seen the -100.000 flag. 

I am validating my pipeline and to do this I took demo data provided by Illumina. I took this https://basespace.illumina.com/projects/27687666/samples. I took the fastq files but I had a look at the BAM files generated by them (I don't know what pipeline they used) and I saw the same flag in the VCF they generated. In case this info helps you.

**Comment by Manuel-DominguezCBG** [comment]
Hello @tamsen, any update about this issue?? No rush, just checking if you figure out this. We can perferly remove the flag from the VCF but if this can be done directly from PISCES, that would be great!! ;)

**Comment by tamsen** [comment]
Hi Sorry! I missed that you added the bam. Hang on.

**Comment by tamsen** [comment]
OK, it looks like a small bug, so that when other filters are activated in a particular combination the SB flag shows up. You have the ssFilter off, and the actual SB being reported is "-100" so PISCES is not finding any real SB in your data.

Thanks for finding this issue. It must have been around a long time. Sorry you have to have the extra step to remove the flag.

**Comment by Manuel-DominguezCBG** [comment]
Ok! Thank you @tamsen. Are you planning to remove the SB flag when the ssFilter is off in a future release? If so, please le me know. I am happy to add an extra step to delete this flag.

Thank you for your help!

**Comment by Manuel-DominguezCBG** [comment]
This command does the bit
`
 bcftools annotate -x FORMAT/SB input.vcf > output.vcf`

I close this issue. Thanks!!
