### ISSUE TITLE
Gemini 5.3.0.0 Nullable object Error

### ISSUE THREAD

**Issue by ShannonDaddy** [tamsen/Pisces#8]
Hi

I got the Nullable object Error when I was using Gemini in Pisces 5.3.0.0,  and I can't figure out why, please help me.

1/20/21 12:01 PM 1  ************* Starting **************
1/20/21 12:01 PM 1  Version:  5.3.0.0.
1/20/21 12:01 PM 1  Command-line arguments: .
1/20/21 12:01 PM 1  "--bam C2004235.flt.trim.bam --genome genome_db/hsa/Genome/ucsc/090520_hg19/SplitGenome/ --samtools samtools-1.9/samtools --outfolder Output/C2004235".
1/20/21 12:01 PM 1  Exception reported:  
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Gemini.BlockFactorySource.GetBlockProvider(Dictionary`2 refIdMapping, String chrom, IWriterSource writerSource, ConcurrentDictionary`2 progressTracker, ConcurrentDictionary`2 categoryLookup, ConcurrentDic
tionary`2 masterIndelLookup, ConcurrentDictionary`2 masterOutcomesLookup, ConcurrentDictionary`2 masterFinalIndels, ChrReference chrReference)
   at Gemini.DataflowReadEvaluator.ProcessBam()
   at Gemini.GeminiWorkflow.Execute()
   at Gemini.Program.ProgramExecution()
   at CommandLine.Application.BaseApplication`1.Execute().
1/20/21 12:01 PM 1  ******************** Ending *********************

The log file and input bam file are attached.

Thanks a lot!
[pisces.zip](https://github.com/tamsen/Pisces/files/5840146/pisces.zip)

**Comment by ShannonDaddy** [comment]
> Hi
> 
> I got the Nullable object Error when I was using Gemini in Pisces 5.3.0.0, and I can't figure out why, please help me.
> 
> 1/20/21 12:01 PM 1 ************* Starting **************
> 1/20/21 12:01 PM 1 Version: 5.3.0.0.
> 1/20/21 12:01 PM 1 Command-line arguments: .
> 1/20/21 12:01 PM 1 "--bam C2004235.flt.trim.bam --genome genome_db/hsa/Genome/ucsc/090520_hg19/SplitGenome/ --samtools samtools-1.9/samtools --outfolder Output/C2004235".
> 1/20/21 12:01 PM 1 Exception reported:
> System.InvalidOperationException: Nullable object must have a value.
> at System.Nullable`1.get_Value() at Gemini.BlockFactorySource.GetBlockProvider(Dictionary`2 refIdMapping, String chrom, IWriterSource writerSource, ConcurrentDictionary`2 progressTracker, ConcurrentDictionary`2 categoryLookup, ConcurrentDic
> tionary`2 masterIndelLookup, ConcurrentDictionary`2 masterOutcomesLookup, ConcurrentDictionary`2 masterFinalIndels, ChrReference chrReference) at Gemini.DataflowReadEvaluator.ProcessBam() at Gemini.GeminiWorkflow.Execute() at Gemini.Program.ProgramExecution() at CommandLine.Application.BaseApplication`1.Execute().
> 1/20/21 12:01 PM 1 ******************** Ending *********************
> 
> The log file and input bam file are attached.
> 
> Thanks a lot!
> [pisces.zip](https://github.com/tamsen/Pisces/files/5840146/pisces.zip)

**Comment by tamsen** [comment]
Hi!

I'm afraid I'm swamped right now and wont have the time to really dig into this until late March (sorry!). In the meantime, this new more linux-friendly version on this fork should be much more friendly to debug on your own if you are comfortable trying. (build instructions and compiler suggestion here: https://github.com/tamsen/Pisces/blob/master/README.md , go to Build instructions section)

I had a quick look at your log you attached and it seems like Gemini does not know its getting a bam. The samples object  in GeminiOptions.used.json says "  

"GeminiSampleOptions": {
    "InputBam": null,
    "OutputBam": null,
    "OutputFolder": null,
    "IntermediateDir": null,
    "RefId": null

So, the nulls in the above looks not good. Perhaps something is not right on your command line? Here's an example Gemini command that worked for me on a quick test, below. Maybe you can use this as an example to sort out your command line.

/rhome/tdunn011/pisces_all/Pisces_5.3.0/GeminiMulti --bam /rhome/tdunn011/bigdata/HomoSapiens/SampleSet1_Titration/12pct-NA12877-r1_S11.bam --genome /rhome/tdunn011/bigdata/Genomes/HomoSapiens/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta --samtools samtools --exePath /rhome/tdunn011/pisces_all/Pisces_5.3.0/Gemini --outFolder /rhome/tdunn011/bigdata/HomoSapiens/SampleSet1_Titration --numProcesses 24 --chromosomes chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY

I'll check back in as soon as I have free time.

best
Tamsen

**Comment by stephanflemming** [comment]
I had the same problem. `--exePath`  was not set correctly. Maybe that helps.

**Comment by tamsen** [comment]
Hi ShannonDaddy,

I tested with your bam and had no issue with v5.3.0.  Here is the command I used.

/rhome/tdunn011/shared/Pisces/Pisces_5.3.0/GeminiMulti --bam /rhome/tdunn011/bigdata/HomoSapiens/PICS8/C2004235.flt.trim.bam --genome /rhome/tdunn011/bigdata/Genomes/HomoSapiens/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta --samtools samtools --exePath /rhome/tdunn011/shared/Pisces/Pisces_5.3.0/Gemini --outFolder /rhome/tdunn011/bigdata/HomoSapiens/PICS8 --numProcesses 24 --chromosomes chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY

I think this is a command-line issue as Stephen suggested. Please try v5.3.0 with the command line I suggest and see how it goes.  I'm going to close this issue. But if you still have the issue, please let me know, and I will dig in some more.

best,
Tamsen
